import { AbpHttpInterceptor, RefreshTokenService, AbpHttpConfigurationService } from 'abp-ng2-module';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import * as ApiServiceProxies from './service-proxies';
import { ZeroRefreshTokenService } from '@account/auth/zero-refresh-token.service';
import { ZeroTemplateHttpConfigurationService } from './zero-template-http-configuration.service';

@NgModule({
    providers: [
        ApiServiceProxies.CasePoliceReportSummariesServiceProxy,        
        ApiServiceProxies.ViewThirdPartyCaseRequestsServiceProxy,
        ApiServiceProxies.DocumentSettingsServiceProxy,
        ApiServiceProxies.VehiclesServiceProxy,
        ApiServiceProxies.FoldersServiceProxy,
        ApiServiceProxies.FileOrgsServiceProxy,
        ApiServiceProxies.OpenAIIntegrationLogsServiceProxy,
        ApiServiceProxies.PromptsServiceProxy,
        ApiServiceProxies.ExpensesClaimsApprovalServiceProxy,
        ApiServiceProxies.DebitNoteItemsServiceProxy,
        ApiServiceProxies.CaseDebitNotesServiceProxy,
        ApiServiceProxies.CreditNoteItemsServiceProxy,
        ApiServiceProxies.InvoiceReportsServiceProxy,
        ApiServiceProxies.CaseCreditNotesServiceProxy,
        ApiServiceProxies.AuditTrailsServiceProxy,
        ApiServiceProxies.AuditEntriesServiceProxy,
        ApiServiceProxies.CaseReportsServiceProxy,
        ApiServiceProxies.AdjusterReportsServiceProxy,
        ApiServiceProxies.WIPReportsServiceProxy,
        ApiServiceProxies.InvoiceItemsServiceProxy,
        ApiServiceProxies.CaseInvoicesServiceProxy,
        ApiServiceProxies.WIPSummaryReportsServiceProxy,
        ApiServiceProxies.CaseExpensesServiceProxy,
        ApiServiceProxies.CaseDeclarationAnswersServiceProxy,
        ApiServiceProxies.CaseThirdPartyVehiclesServiceProxy,
        ApiServiceProxies.CasePoliceReportsServiceProxy,
        ApiServiceProxies.CaseIncidentDetailsServiceProxy,
        ApiServiceProxies.CaseThirdPartyInfosServiceProxy,
        ApiServiceProxies.CaseWorkshopsServiceProxy,
        ApiServiceProxies.WorkshopsServiceProxy,
        ApiServiceProxies.CaseLawyersServiceProxy,
        ApiServiceProxies.CaseClaimsServiceProxy,
        ApiServiceProxies.CaseSearchFeesServiceProxy,
        ApiServiceProxies.StaffsServiceProxy,
        ApiServiceProxies.GroupsServiceProxy,
        ApiServiceProxies.CaseDeclarationAnswersServiceProxy,
        ApiServiceProxies.CaseThirdPartyVehiclesServiceProxy,
        ApiServiceProxies.CasePoliceReportsServiceProxy,
        ApiServiceProxies.CaseIncidentDetailsServiceProxy,
        ApiServiceProxies.CaseThirdPartyInfosServiceProxy,
        ApiServiceProxies.CaseWorkshopsServiceProxy,
        ApiServiceProxies.WorkshopsServiceProxy,
        ApiServiceProxies.CaseLawyersServiceProxy,
        ApiServiceProxies.LawFirmsServiceProxy,
        ApiServiceProxies.InsuredPersonsServiceProxy,
        ApiServiceProxies.HospitalsServiceProxy,
        ApiServiceProxies.CaseInsurersServiceProxy,
        ApiServiceProxies.AuditLogServiceProxy,
        ApiServiceProxies.CachingServiceProxy,
        ApiServiceProxies.ChatServiceProxy,
        ApiServiceProxies.CommonLookupServiceProxy,
        ApiServiceProxies.EditionServiceProxy,
        ApiServiceProxies.FriendshipServiceProxy,
        ApiServiceProxies.HostSettingsServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.LanguageServiceProxy,
        ApiServiceProxies.NotificationServiceProxy,
        ApiServiceProxies.OrganizationUnitServiceProxy,
        ApiServiceProxies.PermissionServiceProxy,
        ApiServiceProxies.ProfileServiceProxy,
        ApiServiceProxies.RoleServiceProxy,
        ApiServiceProxies.SessionServiceProxy,
        ApiServiceProxies.TenantServiceProxy,
        ApiServiceProxies.TenantDashboardServiceProxy,
        ApiServiceProxies.TenantSettingsServiceProxy,
        ApiServiceProxies.TimingServiceProxy,
        ApiServiceProxies.UserServiceProxy,
        ApiServiceProxies.UserLinkServiceProxy,
        ApiServiceProxies.UserLoginServiceProxy,
        ApiServiceProxies.WebLogServiceProxy,
        ApiServiceProxies.AccountServiceProxy,
        ApiServiceProxies.TokenAuthServiceProxy,
        ApiServiceProxies.TenantRegistrationServiceProxy,
        ApiServiceProxies.HostDashboardServiceProxy,
        ApiServiceProxies.PaymentServiceProxy,
        ApiServiceProxies.DemoUiComponentsServiceProxy,
        ApiServiceProxies.InvoiceServiceProxy,
        ApiServiceProxies.SubscriptionServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.UiCustomizationSettingsServiceProxy,
        ApiServiceProxies.PayPalPaymentServiceProxy,
        ApiServiceProxies.StripePaymentServiceProxy,
        ApiServiceProxies.DashboardCustomizationServiceProxy,
        ApiServiceProxies.WebhookEventServiceProxy,
        ApiServiceProxies.WebhookSubscriptionServiceProxy,
        ApiServiceProxies.WebhookSendAttemptServiceProxy,
        ApiServiceProxies.UserDelegationServiceProxy,
        ApiServiceProxies.DynamicPropertyServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyDefinitionServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyServiceProxy,
        ApiServiceProxies.DynamicPropertyValueServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyValueServiceProxy,
        ApiServiceProxies.MainRegistrationServiceProxy,
        ApiServiceProxies.CaseAdjustersServiceProxy,
        ApiServiceProxies.ScopeAssignmentsServiceProxy,
        ApiServiceProxies.DeclarationQuestionsServiceProxy,
        ApiServiceProxies.TwitterServiceProxy,
        ApiServiceProxies.LookupsServiceProxy,
        ApiServiceProxies.CaseExpensesServiceProxy,
        ApiServiceProxies.RegistrationExporterServiceProxy,
        ApiServiceProxies.CaseTypeServiceProxy,
        ApiServiceProxies.BranchServiceProxy,
        ApiServiceProxies.CompanyServiceProxy,
        ApiServiceProxies.RemarkServiceProxy,
        ApiServiceProxies.CommonDropdownServiceProxy,
        ApiServiceProxies.OUOnboardingServiceProxy,
        { provide: RefreshTokenService, useClass: ZeroRefreshTokenService },
        { provide: AbpHttpConfigurationService, useClass: ZeroTemplateHttpConfigurationService },
        { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true },
    ],
})
export class ServiceProxyModule {}
